
package com.example.floppyfish;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity
public class Flashcard
{
    @PrimaryKey(autoGenerate = true)
    public int cardNumber; //Is autogenerated has no real purpose
    public int deckContainer;
    public String value;
    public String answer;

    public Flashcard() {}

    public Flashcard(int deckContainer)
    {
        this.deckContainer = deckContainer;
    }
}

